### ISSUE TITLE
shouldn't `||` be replaced with `&&`

### ISSUE THREAD

**Issue by deadcoder0904** [alkihis/twitter-api-v2-user-oauth2-flow-example#1]
on this line:

https://github.com/alkihis/twitter-api-v2-user-oauth2-flow-example/blob/ce032d65ab43d6bbaa63eff737775942724c5ad1/src/routes/callback.ts#L42

or am i wrong?

**Comment by alkihis** [comment]
No. If any of those statements are true, an error should be thrown.

**Comment by deadcoder0904** [comment]
oh yes, i was thinking like this:

```tsx
if (!(savedState && redirectUri && savedVerifier && savedState === state)) {
```

which does the same thing :)
